baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Maczko Chiropody'
theme = "simple-office"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 2
[[menu.main]]
    identifier = "conditions"
    name = "Conditions"
    url = "/conditions"
    weight = 3
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4
[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 5