# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Simple Office"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Simple Office is a clean and minimalist Hugo theme designed specifically for creating brochure websites for offices, businesses, or professional services. With its sleek and modern design, this theme provides a professional and polished look, perfect for showcasing information about your office, team members, services offered, and contact details."
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Sheldon Codling"
  homepage = "https://www.sheldonc.ca"
